### ISSUE TITLE
不显示，但是删了一行就能运行了

### ISSUE THREAD

**Issue by yuyue31** [daycold1000/boom_gold_flower#1]
我把from hoshino.modules.mgss.mengguisushe import coin删了就能显示内容了，请问这是货币系统吗，会影响后续的内容吗

**Comment by yuyue31** [comment]
还有小伙伴反应喵喵石没了，emmm应该怎么解决，感谢大佬

**Comment by daycold1000** [comment]
> 还有小伙伴反应喵喵石没了，emmm应该怎么解决，感谢大佬

请问是在什么情况下导致货币消失的吗？
注意：功能玩法为，输入 炸金花 后在30秒内输入炸+数字梭哈，然后在爆炸之前使用 拿 拿回石头，爆炸后梭哈的石头全部清零

**Comment by yuyue31** [comment]
感谢大佬，已经解决了，是之前商店的没有安装，请问大佬有群吗，再次感谢大佬



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月10日(周六) 中午11:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [daycold1000/boom_gold_flower] 不显示，但是删了一行就能运行了 (Issue #1)




  
还有小伙伴反应喵喵石没了，emmm应该怎么解决，感谢大佬
  
请问是在什么情况下导致货币消失的吗？
 注意：功能玩法为，输入 炸金花 后在30秒内输入炸+数字梭哈，然后在爆炸之前使用 拿 拿回石头，爆炸后梭哈的石头全部清零

**Comment by daycold1000** [comment]
我的群、机器人已经在2022年11月2日全部解散，现有功能插件只是为了留作纪念备份在这里，希望玩的开心(*^▽^*)
你仍然可以通过邮箱：miao-time@foxmail.com与我聊天~

**Comment by yuyue31** [comment]
好的，大佬您辛苦了，感谢您的插件



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月10日(周六) 中午1:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [daycold1000/boom_gold_flower] 不显示，但是删了一行就能运行了 (Issue #1)




 
我的群、机器人已经在2022年11月2日全部解散，现有功能插件只是为了留作纪念备份在这里，希望玩的开心(^▽^)
